version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 1
  allow:
  - dependency-type: direct
  - dependency-type: indirect
