language: php
sudo: false
cache: composer

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm-nightly
    - php: 7

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install

script: make travis

notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true

after_script: sh -c " if [ -f ./build/logs/clover.xml ]; then php vendor/bin/coveralls; fi"
